"""create tickets table

Revision ID: eb4f534443bf
Revises: 
Create Date: 2026-08-19 12:41:10.770776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4f534443bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###

    # Von Alembic NICHT automatisch generiert: Postgres-ENUM-Typen werden von
    # drop_table() nicht mit entfernt. Ohne diese Zeile würde ein erneutes
    # upgrade mit "type ticket_status already exists" fehlschlagen.
    sa.Enum(name="ticket_status").drop(op.get_bind(), checkfirst=True)
